apiVersion: v1
kind: Service
metadata:
  name: opencredit-backend
  labels:
    app: opencredit
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
  selector:
    app: opencredit
    component: backend 