apiVersion: v1
kind: Service
metadata:
  name: opencredit-frontend
  labels:
    app: opencredit
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
  selector:
    app: opencredit
    component: frontend 