apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencredit-frontend
  labels:
    app: opencredit
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: opencredit
      component: frontend
  template:
    metadata:
      labels:
        app: opencredit
        component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        env: {{ .Values.frontend.env | toYaml | nindent 10 }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: 15
          periodSeconds: 20 